// Tests component creation

type foo is interface( in integer ticker,tocker; out integer bob )
type bar is interface( in string s );


component Radio presents foo {
	
	size = 0;
	
	constructor() {
	}
	
	constructor( in integer startticks ) {
		ticker := startticks;
	}
	
	constructor( in integer startticks; integer framesize ) { 
		ticker := startticks;
	}	
	
	behaviour {
		
	}
}
 
 bob = new Radio( b,v );




