proc mode( real[] i ) : real { return 0.0 }

type TempAveragerIF is interface(	in real input;
									out real output ) 

component TempModeAverager presents TempAveragerIF {
	size = 5
	temps = new real[5] of 0.0
	index = 0

	constructor() {
	}

	behaviour {
		receive temp from input
		temps[index] := temp
		index := index + 1
		if index == size - 1 then {
			send mode( temps ) on output
			index := 0
		}
	}
}
// Instantiate the new averager component
newAverager = new TempModeAverager()
