// Tests copy copy on send for complex types
// Version 2 - includes arrays

type person is struct( string name; integer[] age )

type foo is interface( out person people )
type bah is interface( in person people )

component Connect1 presents foo {
	
	constructor() {
	}
	
	behaviour {
		x = new integer[4] of 3
		p = new person( "al", x )
		send p on people
	}
}
 
component Connect2 presents bah {
	
	constructor() {
	}
	
	behaviour {
		receive p from people
	}
}

f = new Connect1();
g = new Connect2();
connect f.people to g.people;
disconnect g.people







