// Simple Hello World Insense program

// Interface for Hello component
type IHello is interface ( )

// Hello World component
component Hello presents IHello {

	count = 0

	constructor(){}
		
	behaviour {
		//printAny(any("\nHello World "))
		printAny(any(count))
		count := count + 1
	}
} 

type ILauncher is interface ( )
component Launcher presents ILauncher {
                
	constructor(){}
                
	behaviour {
		hello = new Hello()
		stop hello
	}
}

laucher = new Launcher()

