/*
 * Experiment to investigate effects of thread placement and communication
 * between components on performance.
 *
 * Experiment 1: 8 Senders are connected to 8 Receivers with 8 channels. 
 *
 * Copyright (c) 2013, Pavlo Bazilinskyy <pavlo.bazilinskyy@gmail.com>
 * School of Computer Science, St. Andrews University
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

type IReceiver is interface( in integer input )
type ISender is interface( out integer output )

component Sender presents ISender {
	runTime = 1000000	// Amount of times behaviour is to be executed.
	count = 0			// Used to track number of times behaviour has executed.
	
	constructor(){ }

	behaviour {
		// First send an int to a server
		send 0 on output
		
		count := count + 1
		
		// Show percentage done: 50% - 100%
		if (count % (runTime / 2) == 0) then {		
			printInt(100 / (runTime / count))
			printString("% done.\n")
		}
		
		if (count >= runTime) then {
			stop
		}
	}
}

component Receiver presents IReceiver {
	runTime = 1000000	// Amount of times behaviour is to be executed.
	count = 0			// Used to track number of times behaviour has executed.

	constructor(){ }

	behaviour {
		// First receive an int from a client
		receive blank from input
		
		count := count + 1 // Increment a counter of executions of behaviour
		// Show percentage done: 50% - 100%
		if (count % (runTime / 2) == 0) then {		
			printInt(100 / (runTime / count))
			printString("% done.\n")
		}
		// If a limit of execution has been exceeded - stop
		if (count >= runTime) then {
			stop
		}
	}
}

//Insense main
sender1 = new Sender()
sender2 = new Sender()
receiver1 = new Receiver()
receiver2 = new Receiver()

// Connect senders and receiver with channels.
connect sender1.output to receiver1.input
connect sender2.output to receiver2.input